version: '3.7'
services:
  db:
    image: mysql:latest 
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/dump:/docker-entrypoint-initdb.d
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: minhamorada
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
  backend:
    container_name: minhamorada
    build:
        context: ./
        dockerfile: Dockerfile
    volumes:
        - ./:/backend
    ports:
        - '8080:8080'
    restart: always
    working_dir: /backend
    depends_on:
        - db


 